substitutions:
  devicename: "sensor-box"
  update_time: 30s

esphome:
  name: ${devicename}
  name_add_mac_suffix: true
  friendly_name: "Sensor Box"

  project:
    name: alphaars.sensor_box
    version: "1.0.0"

  # Re-apply restored number values to the LD1125H via UART on boot
  on_boot:
    priority: 800
    then:
      - delay: 1s
      - number.set:
          id: LD1125H_mth1
          value: !lambda "return id(LD1125H_mth1).state;"
      - number.set:
          id: LD1125H_mth2
          value: !lambda "return id(LD1125H_mth2).state;"
      - number.set:
          id: LD1125H_mth3
          value: !lambda "return id(LD1125H_mth3).state;"
      - number.set:
          id: LD1125H_rmax
          value: !lambda "return id(LD1125H_rmax).state;"
      - number.set:
          id: LD1125H_Clear_Time
          value: !lambda "return id(LD1125H_Clear_Time).state;"
      - number.set:
          id: LD1125H_Mov_Time
          value: !lambda "return id(LD1125H_Mov_Time).state;"

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    # omit ssid -> auto uses device name with MAC suffix
    password: !secret ap_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components:
      - serial

# UARTs for LD1125H and PMS7003T sensors
uart:
  - id: LD1125H_UART_BUS
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: NONE
  - id: pms_uart
    rx_pin: GPIO4
    baud_rate: 9600

globals:
  - id: LD1125H_Last_Time
    type: time_t
    restore_value: false
    initial_value: "0"
  - id: LD1125H_Last_Mov_Time
    type: time_t
    restore_value: false
    initial_value: "0"
  - id: LD1125H_Clearence_Status
    type: bool
    restore_value: false
    initial_value: "false"

status_led:
  pin:
    number: GPIO2
    inverted: false

interval:
  - interval: 1s
    setup_priority: -200
    then:
      lambda: |-
        if ((time(NULL) - id(LD1125H_Last_Time)) > id(LD1125H_Clear_Time).state) {
          if ((id(LD1125H_Clearence_Status) == false) || (id(LD1125H_Occupancy).state != "Clearance")) {
            id(LD1125H_Occupancy).publish_state("Clearance");
            id(LD1125H_Clearence_Status) = true;
          }
          if (id(LD1125H_MovOcc_Binary).state == true) {
            id(LD1125H_MovOcc_Binary).publish_state(false);
          }
          if (id(LD1125H_Mov_Binary).state == true) {
            id(LD1125H_Mov_Binary).publish_state(false);
          }
        }

# ---------- Clean, short entity names ----------
number:
  - platform: template
    id: LD1125H_mth1
    name: "Motion Threshold 1"
    icon: mdi:cogs
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 60.0
    min_value: 10.0
    max_value: 600.0
    step: 5.0
    set_action:
      - uart.write:
          id: LD1125H_UART_BUS
          data: !lambda |-
            std::string s = "mth1=" + str_sprintf("%.0f", x) + "\r\n";
            return std::vector<uint8_t>(s.begin(), s.end());

  - platform: template
    id: LD1125H_mth2
    name: "Motion Threshold 2"
    icon: mdi:cogs
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 30
    min_value: 5
    max_value: 300
    step: 5
    set_action:
      - uart.write:
          id: LD1125H_UART_BUS
          data: !lambda |-
            std::string s = "mth2=" + str_sprintf("%.0f", x) + "\r\n";
            return std::vector<uint8_t>(s.begin(), s.end());

  - platform: template
    id: LD1125H_mth3
    name: "Motion Threshold 3"
    icon: mdi:cogs
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 20
    min_value: 5
    max_value: 200
    step: 5
    set_action:
      - uart.write:
          id: LD1125H_UART_BUS
          data: !lambda |-
            std::string s = "mth3=" + str_sprintf("%.0f", x) + "\r\n";
            return std::vector<uint8_t>(s.begin(), s.end());

  - platform: template
    id: LD1125H_rmax
    name: "Max Range (m)"
    icon: mdi:arrow-expand-horizontal
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 8
    min_value: 0.4
    max_value: 12
    step: 0.1
    set_action:
      - uart.write:
          id: LD1125H_UART_BUS
          data: !lambda |-
            std::string s = "rmax=" + str_sprintf("%.1f", x) + "\r\n";
            return std::vector<uint8_t>(s.begin(), s.end());

  - platform: template
    id: LD1125H_Clear_Time
    name: "Clearance Delay (s)"
    icon: mdi:timer-sand
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 5
    min_value: 0.5
    max_value: 20
    step: 0.5

  - platform: template
    id: LD1125H_Mov_Time
    name: "Movement Debounce (s)"
    icon: mdi:timer-outline
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 1
    min_value: 0.5
    max_value: 10
    step: 0.5

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: template
    id: LD1125H_Distance
    name: "Distance"
    icon: mdi:signal-distance-variant
    unit_of_measurement: "m"
    accuracy_decimals: 2
    filters:
      - sliding_window_moving_average:
          window_size: 8
          send_every: 2
      - heartbeat: 0.2s

  - platform: bme680
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    address: 0x77
    update_interval: 60s

  - platform: pmsx003
    uart_id: pms_uart
    type: PMSX003
    pm_1_0:
      name: "PM1.0"
    pm_2_5:
      name: "PM2.5"
    pm_10_0:
      name: "PM10"

  - platform: bh1750
    name: "Illuminance"
    update_interval: 60s

  - platform: sgp30
    update_interval: 60s
    eco2:
      name: "eCO2"
    tvoc:
      name: "TVOC"

  - platform: adc
    pin: GPIO34
    name: "MICS5524 (V)"
    update_interval: 10s
    filters:
      - multiply: 3.3

text_sensor:
  - platform: serial
    uart_id: LD1125H_UART_BUS
    id: LD1125H_UART_Text
    name: "LD1125H Raw"
    icon: mdi:format-text
    internal: true
    on_value:
      lambda: |-
        if (id(LD1125H_UART_Text).state.substr(0, 3) == "occ") {
          id(LD1125H_Distance).publish_state(atof(id(LD1125H_UART_Text).state.substr(9).c_str()));
          if ((time(NULL) - id(LD1125H_Last_Mov_Time)) > id(LD1125H_Mov_Time).state) {
            id(LD1125H_Occupancy).publish_state("Occupancy");
            if (id(LD1125H_MovOcc_Binary).state == false) id(LD1125H_MovOcc_Binary).publish_state(true);
            if (id(LD1125H_Mov_Binary).state   == true)   id(LD1125H_Mov_Binary).publish_state(false);
          }
          if (id(LD1125H_MovOcc_Binary).state == false) id(LD1125H_MovOcc_Binary).publish_state(true);
          id(LD1125H_Last_Time) = time(NULL);
          if (id(LD1125H_Clearence_Status) == true) id(LD1125H_Clearence_Status) = false;
        } else if (id(LD1125H_UART_Text).state.substr(0, 3) == "mov") {
          id(LD1125H_Distance).publish_state(atof(id(LD1125H_UART_Text).state.substr(9).c_str()));
          id(LD1125H_Occupancy).publish_state("Movement");
          if (id(LD1125H_MovOcc_Binary).state == false) id(LD1125H_MovOcc_Binary).publish_state(true);
          if (id(LD1125H_Mov_Binary).state   == false)  id(LD1125H_Mov_Binary).publish_state(true);
          id(LD1125H_Last_Mov_Time) = time(NULL);
          id(LD1125H_Last_Time) = time(NULL);
          if (id(LD1125H_Clearence_Status) == true) id(LD1125H_Clearence_Status) = false;
        }

  - platform: template
    id: LD1125H_Occupancy
    name: "Occupancy"
    icon: mdi:motion-sensor

binary_sensor:
  - platform: status
    name: "Status"

  - platform: template
    id: LD1125H_MovOcc_Binary
    name: "Occupancy or Movement"
    device_class: occupancy

  - platform: template
    id: LD1125H_Mov_Binary
    name: "Movement"
    device_class: motion
